spring.application.name=desi-jeques

spring.datasource.url=jdbc:mysql://localhost:3306/desijeques?useSSL=false&serverTimezone=UTC
spring.datasource.username=desi
spring.datasource.password=desi123

spring.jpa.defer-datasource-initialization=true

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.thymeleaf.cache=false
#
##ENTORNO DE PRUEBA COLOX
#spring.datasource.url=jdbc:mysql://localhost:3306/desi_jeques
#spring.datasource.username=root
#spring.datasource.password=

#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true
#server.port=8080
#spring.web.resources.static-locations=classpath:/static/